# Generated by Django 4.2.7 on 2024-11-30 05:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Black',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('영화', '영화'), ('음악', '음악'), ('책', '책'), ('유튜브', '유튜브'), ('OTT', 'OTT'), ('공연', '공연')], max_length=5)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('information', models.TextField()),
                ('color', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('frame', models.CharField(choices=[('TREE', 'TREE'), ('MAN', 'SNOW'), ('HAT', 'HAT'), ('YEAR', 'YEAR'), ('MAN', 'MAN'), ('STAR', 'STAR')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
