# Generated by Django 4.2.7 on 2024-12-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="black",
            name="frame",
            field=models.CharField(
                choices=[
                    ("TREE", "TREE"),
                    ("SNOW", "SNOW"),
                    ("HAT", "HAT"),
                    ("YEAR", "YEAR"),
                    ("MAN", "MAN"),
                    ("STAR", "STAR"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="white",
            name="frame",
            field=models.CharField(
                choices=[
                    ("TREE", "TREE"),
                    ("SNOW", "SNOW"),
                    ("HAT", "HAT"),
                    ("YEAR", "YEAR"),
                    ("MAN", "MAN"),
                    ("STAR", "STAR"),
                ],
                max_length=5,
            ),
        ),
    ]
