# Generated by Django 4.2.7 on 2024-11-30 05:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='White',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('여행지', '여행지'), ('음식', '음식'), ('밈', '밈'), ('사진', '사진'), ('아이템', '아이템'), ('룩', '룩'), ('어플', '어플'), ('스포츠', '스포츠')], max_length=5)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('frame', models.CharField(choices=[('TREE', 'TREE'), ('MAN', 'SNOW'), ('HAT', 'HAT'), ('YEAR', 'YEAR'), ('MAN', 'MAN'), ('STAR', 'STAR')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
