# Generated by Django 3.2.8 on 2024-12-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_black_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='black',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='black',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='white',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='white',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
